### ISSUE TITLE
Помечать пользователей, которым не отправляется смс

### ISSUE THREAD

**Issue by biomancer** [fbkinfo/rosvybory#319]
Если ошибка 207 в Work Logs, то надо чтобы люди знали об этом не перечитывая все логи

**Comment by khodzha** [comment]
Нужно как-то выделять пользователей или логи с ошибкой 207?

**Comment by stiff** [comment]
Пользователей, потому что это означает что нужно исправить телефон у пользователя. А после изменения можно сбрасывать флаг, или после успешной доставки. А при рассылке можно показывать, что вот этим выбранным пользователям в прошлый раз не доставилось :)

**Comment by eremeye** [comment]
Можно писать у всех пользователей, кто и когда последний раз сообщение пользователю отправил и статус этого сообщения.

—
Егор Еремеев
Отправлено с iPhone

**Comment by biomancer** [comment]
Егор, это уже другой уровень задачи, есть такая необходимость?
В данном случае цель, как я понимаю, - проинформировать координатора, что кому-то смс не уходят. Просто чтобы он имел ввиду, что этот человек не координируется. Оставаясь в рамках существующих решений, визуально это можно сделать через подсветку красным телефона пользователя (как в заявках при неподтверждённом номере). Также полезна была бы полезна какая-то система внутренней нотификации для сообщения об этом, но т.к. её нет, можно хотя бы сообщать о возникших ошибках не email тому, кто рассылал.

Итого, что в данный момент нужно по этому таску:
- Визуально помечать пользователей, которым не дошло смс, в списке пользователей и на странице отправки смс. Если это хранить в отдельном флаге, также можно сразу и фильтр сделать по нему на странице пользователей, это легко. Устанавливать и снимать по логике, которую описал @stiff. 
- По итогам обработки посылать сообщение на email отправителя о проблемах с доставкой смс, без личных данных, - можно указать количество и ссылку на сайт, где это можно посмотреть подробнее, например, на список пользователей с включённым фильтром по этому флажку битого телефона.

**Comment by eremeye** [comment]
Такой функционал, как я написал, хорошо было бы к следующему крупному релизу, как часть CRM. 

Сейчас флаг, о том, что неправильный телефон - это хорошее решение.

—
Егор Еремеев
Отправлено с iPhone
