### ISSUE TITLE
В Android невозможно ввести номера желаемых УИКов

### ISSUE THREAD

**Issue by biomancer** [fbkinfo/rosvybory#331]
В форме подачи заявки в разделе "В каком качестве вы готовы участвовать в общественном контроле за выборами?" даже при нажатых чекбоксах не удаётся вводить текст в поле "Номера желаемых УИК".

**Comment by biomancer** [comment]
Проверил на android 4.1 - не работает во встроенном браузере, в Chrome срабатывает нормально

Не удалось повторить на ipad и iphone, всё работает.

**Comment by ghost** [comment]
Отправил Pull request с исправлением - https://github.com/fbkinfo/rosvybory/pull/333
В android 2.3.5 в стандартном браузере проблема ушла.

**Comment by biomancer** [comment]
Спасибо, принял. Обнаружил при проверке другой баг, похоже, с той же причиной - в разделе Текущий статус в системе избирательных комиссий можно редактировать disabled поля, без установки соответствующей галки, пока оставлю issue открытым.
